# Generated by Django 2.1.2 on 2018-10-29 10:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_main', '0004_locationlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationlist',
            name='locations',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
