# Generated by Django 2.1.2 on 2018-10-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_main', '0005_auto_20181029_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='annual_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='monthly_price',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='A great product.'),
        ),
    ]
