# Generated by Django 2.1.2 on 2018-10-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_main', '0006_auto_20181029_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frequency',
            field=models.CharField(default='monthly', max_length=20),
        ),
    ]
