# Generated by Django 2.1.2 on 2018-10-30 06:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_main', '0007_product_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
