# Generated by Django 2.1.2 on 2018-11-09 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_main', '0008_product_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
